.\" $Id: rem.1,v 1.2 1996-04-28 02:02:01 dfs Exp $
.TH REM 1 "26 February 1991"
.UC 4
.SH NAME
rem \- run 'remind' with a default reminder file
.SH SYNOPSIS
.B rem
[\-F \fIfilename\fR] [\fIremind_options\fR] [\fIremind_params\fR]
.SH DESCRIPTION
.B Rem
runs the \fBremind\fR program with a default reminder file of
"$HOME/.reminders".  You can supply remind options on the command line,
as well as a date specification, just as with \fBremind\fR.

If you don't want to use the default filename, you can override it with
the "-F" option, followed by a space and a filename.  (This, however,
defeats the purpose of \fBrem\fR)
.PP
For example, typing:
.PP
.nf
	rem -c 1 jan 1992
.fi
.PP
has the same effect as typing:
.PP
.nf
	remind -c $HOME/.reminders 1 jan 1992
.fi
.PP
.SH AUTHOR
David F. Skoll
.SH SEE ALSO
remind, kall

