#!/bin/sh
cd /home/dfs/Software/Remind.git || exit 1

rm -f .git/COMMIT_EDITMSG

git update-server-info && cd .git && rsync --archive --verbose --progress --delete ./ dianne.skoll.ca:web/projects/remind/git/Remind.git/
exit $?

