#!/bin/sh

#$Id: unconfigure,v 1.1 1998-01-17 03:58:13 dfs Exp $
echo "Unconfiguring Remind..."
echo rm -f config.cache config.log config.status src/Makefile src/config.h
rm -f config.cache config.log config.status src/Makefile src/config.h
exit 0
