#!/bin/sh
# PostScript calendar shell script
#
# This file is part of REMIND.
# Copyright (C) 1992-1997 by David F. Skoll
# Copyright (C) 1999 by Roaring Penguin Software Inc.

# $Id: calps,v 1.2 1999-04-05 17:35:17 dfs Exp $

echo "Content-type: application/postscript"
echo

$REMIND -p /dev/null | $REM2PS -e -c3
exit 0
