#!/bin/sh
# PostScript calendar shell script
#
# This file is part of REMIND.
# Copyright (C) 1992-2018 by Dianne Skoll

echo "Content-type: application/postscript"
echo

$REMIND -p $DIR/blank.rem | $REM2PS -e -c3 -l
exit 0
