#!/bin/sh
# Hebrew date shell script
#
# This file is part of REMIND.
# Copyright (C) 1992-2018 by Dianne Skoll

echo Content-type: text/html
echo ""

cat <<EOM
<HTML>
<HEAD>
<TITLE>Hebrew date</TITLE>
</HEAD>
<BODY>

<H1>Hebrew date</H1>

EOM

$REMIND -arqh $DIR/hebdate.rem

echo "</BODY>"
echo "</HTML>"
exit 0
