#!/bin/sh
# Moon shell script
#
# This file is part of REMIND.
# Copyright (C) 1992-1997 by David F. Skoll
# Copyright (C) 1999-2000 by Roaring Penguin Software Inc.

# $Id: moon,v 1.3 2000-02-18 03:46:40 dfs Exp $

echo Content-type: text/html
echo
echo "<HTML>"
$REMIND $DIR/moon.rem
echo "</HTML>"
exit 0

