#!/bin/sh
# Sunrise shell script
#
# This file is part of REMIND.
# Copyright (C) 1992-1997 by David F. Skoll
# Copyright (C) 1999-2000 by Roaring Penguin Software Inc.

echo Content-type: text/html
echo
echo "<HTML>"
$REMIND -arqh $DIR/sunrise.rem
echo "</HTML>"

exit 0
