#!/bin/sh
# Sunset shell script
#
# This file is part of REMIND.
# Copyright (C) 1992-1997 by Dianne Skoll
# Copyright (C) 1999-2000 by Roaring Penguin Software Inc.

echo Content-type: text/html
echo
echo "<HTML>"
$REMIND -arqh $DIR/sunset.rem
echo "</HTML>"

exit 0
