#!/bin/sh
# Sunset shell script
#
# This file is part of REMIND.
# Copyright (C) 1992-2018 by Dianne Skoll

echo Content-type: text/html
echo
echo "<HTML>"
$REMIND -arqh $DIR/sunset.rem
echo "</HTML>"

exit 0
