#!/usr/bin/perl
eval 'exec perl -S $0 ${1+"$@"}'
        if $running_under_some_shell;

use strict;
use warnings;

my $reminder_file = $ENV{'DOTREMINDERS'} || $ENV{'HOME'} . '/.reminders';

my @cmd;
my $thing;
push(@cmd, 'remind');
while ($thing = shift(@ARGV)) {
    last unless ($thing =~ /^-/);
    push(@cmd, $thing);
}
push(@cmd, $reminder_file);
push(@cmd, $thing) if (defined($thing) && ($thing ne ''));
push(@cmd, @ARGV);

exec(@cmd);


