#!/bin/sh
#
# rem - by David Skoll - 26 February 1991
#
# $Id: rem,v 1.1 1998-01-15 02:50:21 dfs Exp $
#
# This script runs 'remind' with a default reminder file assumed.  You
# can override the default by using "rem -F newfile ..."  (But why would
# you use rem unless you wanted to accept the default??)

# ------ You may wish to change the defaults below this line ------

# The default reminder file
DEFAULT=$HOME/.reminders

# The executable file (you may wish to change this to /usr/local/bin/remind
# or whatever.
EXECUTABLE=remind

# No options yet
OPTIONS=""

# No parameters yet
PARAMETERS=""

# ------ You shouldn't change anything below this line -----

# Scan for options
while test "$1" != ""
do
	case $1 in

		-F) DEFAULT=$2
		    shift
		    shift ;;

		-*) OPTIONS="$OPTIONS $1"
		    shift ;;

		*) PARAMETERS=$*
		   break ;;
	esac
done

$EXECUTABLE $OPTIONS $DEFAULT $PARAMETERS
